POST http://localhost:3333/product
Content-Type: application/json

{
    "title": "Produto vermelho",
    "description": "Descrição teste",
    "imageUrl": "iVBORw...",
    "height": 1.80,
    "width": 1.50,
    "price": 0.01
}

###
GET http://localhost:3333/products?search=
Authorization: Bearer 

###
PUT http://localhost:3333/product/78b00cd1-2e71-4d3d-824b-d568162db079
Content-Type: application/json

{
    "title": "Produto azul",
    "description": "Descrição teste",
    "imageUrl": "iVBORw...",
    "height": 1.80,
    "width": 1.50,
    "price": 0.01
}

### 
DELETE http://localhost:3333/product/0f128eac-9bb9-4cab-b4fe-7ed83999787a

###
POST http://localhost:3333/user
Content-Type: application/json

{
    "username": "Carlos Ruiz",
    "email": "carlosruiz@teste.com",
    "password": "senhateste123"
}

###
GET http://localhost:3333/users?search=

###
PUT http://localhost:3333/user/6374d92b-1c15-4201-9b77-9fb0dbdbc319
Content-Type: application/json

{
    "username": "Carlos Ruiz Lopes",
    "email": "carlosruiz10@teste.com",
    "password": "senhateste1234"
}

### 
DELETE http://localhost:3333/user/6374d92b-1c15-4201-9b77-9fb0dbdbc319

###
POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "josepaulo@teste.com",
    "password": "senhateste"
}