POST https://criacril-api-nodejs.onrender.com/product
Content-Type: application/json

{
    "title": "Agora foi mlk",
    "description": "Descrição teste",
    "imageUrl": "urlDaImagem",
    "height": 1.80,
    "width": 1.50,
    "price": 0.01
}

###
GET https://criacril-api-nodejs.onrender.com/products?search=produto

###
PUT https://criacril-api-nodejs.onrender.com/product/4aaa4d91-1e00-4346-a9b4-15da28a0ca21
Content-Type: application/json

{
    "title": "agora foi atualizado mlk",
    "description": "asfsafs",
    "imageUrl": "saasff.org",
    "height": 3.00,
    "width": 0.50,
    "price": 10.00
}

### 
DELETE https://criacril-api-nodejs.onrender.com/product/4aaa4d91-1e00-4346-a9b4-15da28a0ca21